### PR TITLE
Ensure the org report always lists commodities with the same ordering

### LINKED ISSUE #1706: baseline/cmd-org.test fails
I see:

```
/usr/bin/python2.7 "/home/tbm/ledger/test/RegressTests.py" "/home/tbm/ledger/ledger" "/home/tbm/ledger" "/home/tbm/ledger/test/baseline/cmd-org.test"

FAILURE in output from /home/tbm/ledger/test/baseline/cmd-org.test:
--
$ledger -f "/home/tbm/ledger/test/baseline/cmd-org.test" org
--
  @@ -5,8 +5,6 @@
   |||Test 3|*|D|-20.00 EUR|0.00 EUR| Payee: Test 3
   |12-Mar-25|99|Test 4|*|E|30.00 GBP|30.00 GBP|
   ||||*|F|-30.00 GBP|0.00 GBP|
  -|12-Mar-26|test|Test 5|*|G|1 AAA|0.00 GBP|
  -|||||||1 AAA|
  -||||*|H|$-10|0.00 GBP|
  +|12-Mar-26|test|Test 5|*|G|1 AAA|1 AAA|
  +||||*|H|$-10|1 AAA|
   |||||||$-10|
  -|||||||1 AAA|
E[cmd-org.test]STDERR:
```

### PR DESCRIPTION
**Pull request by jwiegley**
Fixes #1706

### CODE REVIEW

**Comment by jwiegley** [comment]
This may not be entirely correct yet. We now stabilize the ordering based on the results of calling `name()` for each commodity, but this may only be the base name, not the entire name as it might appear when using `--lots`. In that case, perhaps we need to fully enable lot reporting locally before asking for the name.

**Comment by tbm** [comment]
@mbudde can you review this change?

**Comment by jwiegley** [comment]
@tbm @mbudde Reading this code more carefully, the report is a hack. We're using the main logic to emit the "first line of a posting" (which works if it's a single amount), but then we're trying to take the balance, sort it the way the report would have sorted it, skip the first line, and then emit what comes after.

The code is extremely fragile! The sorting in the main logic is not the same as the sorting being done here.

I don't know the best way to fix this right now, and so can only recommend we disable this report until a better implementation appears. The formatter provided by `format.cc` needs to accept a template for what to do in the case of subsequent lines in multi-commodity balances.

That way that it's done for regular register reports right now is also hack: we use this `justify` function to tell the amount printer how much whitespace it should create to the left of each subsequent line in the balance report. This is terrible! It should be handled by a formatting line specifically for these other lines.

**Comment by tbm** [comment]
@jwiegley removed the `org` command in f0dacdb22f2888 so I'm closing this PR.

**Pull request closed without merging**
