### PR TITLE
--force-color does not require anymore --color.

### PR DESCRIPTION
**Pull request by thdox**
This was reported as [Bug #1109](http://bugs.ledger-cli.org/show_bug.cgi?id=1109).

Can somebody ( @jwiegley ? ) can please review this one. My solution was easy to implement, but I may have introduced side effects, even if tests are passing ?

### CODE REVIEW

**Comment by afh** [comment]
The changes look good to me :+1: 

@thdox can you please rebase this PR from next, so we can get it properly merged…

It might be worthwhile to add another test to `test/baseline/opt-force-color.test`
to verify that no ANSI color codes are printed when the `--force-color` options is *not* set, e.g.:
```
test bal
         0.350 VMMXX  Assets:Investments:Vanguard:VMMXX
              $-0.35  Income:Dividends:Vanguard:VMMXX
--------------------
              $-0.35
         0.350 VMMXX
end test
```

**Comment by davelab6** [comment]
@thdox please rebase :)

**Comment by thdox** [comment]
Not yet ready for merge.... CheckBaselineTests is complaining. It is late here, will go to bed.

**Comment by thdox** [comment]
1. Rebase is now up-to-date (1st and 2nd commits)
2. I have added the test asked by @afh (3rd commit 93dfc1278dba7e6003b6f55386e91d865380a983)
3. Travis checks are passing now. I had some difficulties to understand that CheckBaselineTests wanted an independent test of --color. (4th commit 30e79a8a10ab53f1cd882e5e6aaa1edfbc667244)

**Pull request merged**
