### PR TITLE
Bugzilla 1105

### PR DESCRIPTION
**Pull request by thdox**

### CODE REVIEW

**Comment by afh** [comment]
Good changes, @thdox. It appears that these changes are irrelevant for Travis CI, how about adding `[ci skip]` to the commit messages? :)

**Comment by thdox** [comment]
> how about adding [ci skip] to the commit messages? 

Yes, I know, but randomly forget to do it in my workflow. 
I have followed instructions in https://groups.google.com/d/msg/ledger-cli/8CwyfPUe3vk/64PRc2jGLigJ and I create file ${LEDGER_SOURCE}/.git/hooks/prepare-commit-msg
But this does not add "[ci skip]" apparently. Maybe because I am using magit? Help appreciated.

**Comment by thdox** [comment]
@afh I found that prepare-commit-msg must be executable. I did the change. But now magit fails with "no such file or directory" error.

**Comment by afh** [comment]
@thdox Yes, it must an executable script, which `tools/prepare-commit-msg` is. It might be a good idea to symlink to it from `.git/hooks/` so that future improvements to said script take effect automatically.

The `prepare-commit-msg` hook expects two arguments:
1. The file that has the commit message
2. a description of the commit message's source, e.g. `merge`

Ha, I just gave myself the answer to a question I've been having with said script (｡◕‿◕｡)
I hope I find some time today to make that change, test it, and push it to next.

**Pull request merged**
