### PR TITLE
Add instructions for Fedora 20.

### PR DESCRIPTION
**Pull request by thdox**
[ci skip]

### CODE REVIEW

**Comment by afh** [comment]
I'd like to phase out `acprep` as a build tool and would much more prefer if people use `cmake` directly. I'm in the final stages of re-working the CMakeLists.txt files and adding documentation.

**Comment by thdox** [comment]
My point is helping Fedora users to know what are the packages needed to be able to compile Ledger.
If your new CMakeLists.txt is dealing with Fedora, I have no issue at all to close this pull request.

**Comment by afh** [comment]
I'm working on improving the documentation regarding the requirements, which I think serves users of all platforms. The improved `CMakeLists.txt` doesn't specifically handle any distribution – the maintenance overhead would be too much if you ask me – but generically supports all of them.

I got side-tracked trying to fix an issue with [lcov](https://github.com/linux-test-project/lcov) so the changes are pending; if you like you can have a look my [`pull/cmake`](https://github.com/afh/ledger/tree/pull/cmake) branch (not that it's lacking the aforementioned documentation).

**Comment by thdox** [comment]
I had a look to your pull/cmake branch. To my understanding, your changes are really focusing on the *during* compilation part. This pull request is mainly focusing on *before* compilation part, by adding all the linux packages that are a pre-requisite. Why not accepting this pull request, at least to track the linux packages that are needed, and when refactoring of acprep will take place up to the point of dealing with pre-requisite, then they will be there to be used? My 2 cents. I will not take it personal if this pull request is rejected.

**Comment by afh** [comment]
Sure, I have no intentions on refactoring acprep and would prefer if the effort spent on maintaining acprep is spent on documenting the build and installation instructions in `README.md` and `INSTALL.md`.

**Pull request merged**
