### PR TITLE
Fix using day-of-week names for `xact` command.

### PR DESCRIPTION
**Pull request by kanreki**
Also fix end-of-command boundary checks for keywords "at", "to", etc.

### CODE REVIEW

**Review by tbm — COMMENTED** [review]
Are there test cases to go with that?

**Comment by kanreki** [comment]
I'll add something to baseline/cmd-entry.

By the way, I apologize for mixing in the additional commit regarding the "Cheetah" doc. I didn't realize that pull requests work this way (I have very little Github experience). Shall I remove that change, and maybe send it in again separately later?

Thank you for your prompt response to my first attempt.

**Comment by tbm** [comment]
> Shall I remove that change, and maybe send it in again separately later?

That would be great

**Comment by tbm** [comment]
fwiw @kanreki there was no need to close this and open a new one.  You can edit existing pull requests.  You can do "git rebase" on your end and then do a "git push --force" to update.

It's all a bit complicated the first time, but works well once you've figured it out.

**Comment by kanreki** [comment]
Thanks for the tip!

Yeah, I figured there must be a way. But I decided to keep things dead simple in this case, until I get a bit more facile with it.

**Pull request closed without merging**
