### PR TITLE
Update utfcpp to 3.2.3

### PR DESCRIPTION
**Pull request by afh**
This PR improves and replaces #2180 by squashing utfcpp as a subtree into ledger.

### CODE REVIEW

**Review by tbm — APPROVED** [review]
Thanks so much!

**Comment by tbm** [comment]
Hmm, "This branch cannot be rebased due to conflicts"

**Comment by tbm** [comment]
I merged this manually by copying `/v3` over, doing `git add` and `git rm` on the old tree.  I copy this works...

**Comment by afh** [comment]
Not sure what the issue is with with subtree and GitHub rebase merge…
Thanks for merging, @tbm 🙂! Looks like we're making great progress towards a new release 🎉

**Pull request closed without merging**
