### PR TITLE
Add display_account_note format element

### PR DESCRIPTION
**Pull request by matclab**
It allows to display account note in register command (and not only the
post or transaction note)

### CODE REVIEW

**Comment by matclab** [comment]
Shall I open a ticket accordingly ?

**Comment by matclab** [comment]
Ok, in the process of reading the code, I just understand that `display_account.note` does the trick !!!

**Comment by tbm** [comment]
Can you check if this is properly documented, and if not, submit a PR with a doc improvement?

**Comment by tbm** [comment]
I don't know either, sorry

**Comment by matclab** [comment]
First try in #2364.

Looks like there are other functions in need of doc.

**Pull request closed without merging**
