### PR TITLE
Balance assignment on date

### LINKED ISSUE #2273: What does the expr argument do in account_t::amount?
I am thinking about adding a feature that would involve getting an account balance based on a filtered set of postings. I came across the [account_t::amount](https://github.com/ledger/ledger/blob/d556f3bcb10269ae6dc746ab75b6332cafb21b89/src/account.cc#L613) method which takes a expr_t parameter. It appears that this expr_t will modify a posting amount before it is added to the account total. However, it does not appear this would jive well with the way the account total is computed, that is, by updating a previously computed account total. So I believe this causes two issues:

1. The `account_t::amount` method, when called with an expr argument, will not compute the entire account total based on expr. Only postings not included since the most recent call to `account_t::amount` will reflect expr. This could lead to unexpected results if a user makes use of the expr argument.
2. The amount method could give unexpected results if a previous invocation of `account_t::amount` used the expr argument as some postings may be factored into the total with the old expr.

Is this intended behavior? Or is there some safeguard to prevent this that I missed? It is difficult for me to know whether this is intended since I cannot find any call to `account_t::amount` that uses the expr argument.

If the current behavior is not intended, then I believe a fix would be relatively easy: whenever the expr argument exists, recompute the total from scratch and do not affect the totals stored in `xdata_->self_details`.

### PR DESCRIPTION
**Pull request by dbear496**
This changes the behavior of balance assignment/assertion to take into consideration the date of the posting. When computing the account balance for the purpose of balance assignment, the account postings are filtered to only include those that occur on or before the date of the balance assignment.

My practical use case is I have a journal file that is automatically generated/updated by a script, and then I include this generated journal in my main journal. So it is quite normal for my larger journal to appear out of order as some generated transactions are more recent than some manually entered transactions even though all the generated transactions appear first in the journal. Before this PR, a balance assignment in the manual part of the journal would be affected by newer transactions in the generated journal. On top of that, the posting amount that is computed from the balance assignment would change each time I update the generated journal. This PR fixes this so I can use balance assignments in the manual journal and they will only be affected by transactions from the generated journal that have an earlier (or same) date.

Unfortunately, this does not help me put balance assignments in the generated journal as they will never be affected by postings that are parsed later (in the manually-entered part of the journal). Doing so could lead to ambiguities in computing balance assignments.

As a bonus, I fixed a bug that was left over from PR #1857. And I fixed #2273 even though I am still only 95% sure that it was broken in the first place as I haven't yet seen any comments on that issue.

### CODE REVIEW

**Comment by jwiegley** [comment]
It is part of the design of Ledger that anything syntactic is based on the actual ordering of transactions in the journal, and not the meaning of things like "dates" — even though I agree that this can become counter-intuitive at times.

My suggestion would be to use Ledger itself to sort the data that you import, so that your balance assertions can be applied to the expected transactions, rather than to add new logic like this to Ledger itself, since no other aspect of Ledger incorporates design elements like this.

**Comment by dbear496** [comment]
@jwiegley, now that you mention it, I agree that ordering by date for the purpose of balance assertions is completely arbitrary. However, I still do not quite understand how to achieve the use case in the OP by "using Ledger itself to sort the data that you import"; perhaps you can explain further.

Keep in mind that the imported data _is already sorted_, and the manual section of the journal is also practically sorted. But when the two sections are combined by `include`ing the imported data from the manual section, the the combined result is unsorted. Here is a minimal example of the use case:

```
# generated.ldg

2024-01-15
  income:job  $-2000.00
  assets:checking  $2000.00

2024-02-15
  income:job  $-2000.00
  assets:checking  $2000.00

2024-03-15
  income:job  $2000.00
  assets:checking  $2000.00
```

```
# manual.ldg

include generated.ldg

2024-01-20
  expenses:groceries  $100.00
  assets:checking  $-100.00

# here I balance my bank statement
2024-02-01
  assets:checking  $0 = $1900.00

2024-02-18
  expenses:car repair  $500.00
  assets:checking  $-500.00

# and I balance my bank statement again
2024-03-01
  assets:checking  $0 = $3400.00

# and this one is fine
2024-04-01
  assets:checking  $0 = $5400.00
```

Running `ledger --args-only -f manual.ldg bal`:
```
While parsing file "/tmp/tmp.GqPyNX8cUB/manual.ldg", line 9:
While parsing posting:
  assets:checking  $0 = $1900.00
                        ^^^^^^^^
Error: Balance assertion off by $-4000.00 (expected to see $5900.00)
While parsing file "/tmp/tmp.GqPyNX8cUB/manual.ldg", line 17:
While parsing posting:
  assets:checking  $0 = $3400.00
                        ^^^^^^^^
Error: Balance assertion off by $-2000.00 (expected to see $5400.00)
```

Because of this error, it is not even possible to "use Ledger itself to sort the data that you import". And besides, that would require running a pass to merge the manual/generated sections every time I update the journal, which is not user friendly at all.

**Comment by dbear496** [comment]
Perhaps it would be possible to add a command line option to specify the sort order to use for evaluating balance assertions. That way, evaluating it based on the date is not arbitrarily hard-coded.

**Comment by dbear496** [comment]
Since the desired (default) behavior is to evaluate balance assertions based on the original order of transactions, I think it would be good to add a test case for that. (It's just a bit odd that I made this PR without breaking any existing test cases.)

**Comment by jwiegley** [comment]
You are right that including from two sources creates an impossible scenario for the current implementation. This is why I created support for UUID-based shadowing:

If two transactions, possibly in different files, have the same UUID metadata tag (i.e., UUID: some-string-you-create), Ledger will check that they are equal (except for soft data, like balance assertions), but otherwise all but the first are ignored.

This allows you to track the same transaction by multiple "views", such as in different files and with a different balance assertion on each, so long as the amounts reflected and the UUID are identical.

**Comment by dbear496** [comment]
That is an interesting idea to use the UUID tag. If I do that, would I have to keep around all the old versions of the generated file and manually include the most recent version before each balance assertion?

**Comment by dbear496** [comment]
If we decide to reject this PR, then I think we should consider cherrypicking fac14ced2f916549f8c38a5084f6a7b8f1bf2652 and af24ffd407ba18d8711b0a28fb678a20fb89479e.

**Comment by jwiegley** [comment]
> That is an interesting idea to use the UUID tag. If I do that, would I have to keep around all the old versions of the generated file and manually include the most recent version before each balance assertion?

I don't think I fully understand this question. Why wouldn't you keep around all past data?

**Comment by dbear496** [comment]
> I don't think I fully understand this question. Why wouldn't you keep around all past data?

"Keeping around all past data" and "keeping around all old versions of a file" are very different. If I use the UUID feature instead of the filtered balance assertion, then my example above would turn into this:

```
# generated_2024-02-01.ldg

2024-01-15
  ; UUID: 11111111
  income:job  $-2000.00
  assets:checking  $2000.00
```
```
# generated_2024-03-01.ldg

2024-01-15
  ; UUID: 11111111
  income:job  $-2000.00
  assets:checking  $2000.00

2024-02-15
  ; UUID: 22222222
  income:job  $-2000.00
  assets:checking  $2000.00
```
```
# generated_2024-04-01.ldg

2024-01-15
  ; UUID: 11111111
  income:job  $-2000.00
  assets:checking  $2000.00

2024-02-15
  ; UUID: 22222222
  income:job  $-2000.00
  assets:checking  $2000.00

2024-03-15
  ; UUID: 33333333
  income:job  $2000.00
  assets:checking  $2000.00
```

```
# manual.ldg

2024-01-20
  expenses:groceries  $100.00
  assets:checking  $-100.00

include generated_2024-02-01.ldg

# here I balance my bank statement
2024-02-01
  assets:checking  $0 = $1900.00

2024-02-18
  expenses:car repair  $500.00
  assets:checking  $-500.00

include generated_2024-03-01.ldg

# and I balance my bank statement again
2024-03-01
  assets:checking  $0 = $3400.00

include generated_2024-04-01.ldg

# and this one is fine
2024-04-01
  assets:checking  $0 = $5400.00
```

Notice that I have to keep all the old versions of the generated file even though newer versions contain all the same data.

**Comment by jwiegley** [comment]
I see. There is another recent PR that offers the ability to print hashes of entry data, that would be stable in this situation and could be used as the UUID...

**Pull request closed without merging**
