### PR TITLE
Update utfcpp to 3.2.1

### PR DESCRIPTION
**Pull request by afh**
The local copy of [utfcpp](https://github.com/nemtrif/utfcpp) (v2_0) seems rather old, if not "outdated" given that the latest version is [3.2.1](https://github.com/nemtrif/utfcpp/releases/tag/v3.2.1) released on June 6th, 2021.

ℹ️  The majority of commits in this PR come from the utfcpp subtree; the following commands were used to update utfcpp:

```
% git subtree add --prefix lib/utfcpp/v3 https://github.com/nemtrif/utfcpp.git v3.2.1
% git rm -rf lib/utfcpp/v2_0
```

### CODE REVIEW

**Review by tbm — APPROVED** [review]
Thanks, and sorry for the delay.

**Comment by tbm** [comment]
I'm seeing "This branch cannot be rebased due to conflicts".  @afh can you just merge this yourself or update the PR.

**Comment by tbm** [comment]
@afh can you update or merge this

**Comment by tbm** [comment]
@afh are you still there?

**Comment by tbm** [comment]
@afh can you update this PR

**Comment by tbm** [comment]
@afh can you update this PR, merge it yourself or tell me how to merge it (I tried and failed).

I'd like to get a new ledger release out soon.

**Comment by tbm** [comment]
I failed to merge this. @afh can you tell me how or merge yourself or update?

I'd like to make a new release soon

**Comment by tbm** [comment]
@afh can you merge this or update the PR?

I'd like to get a new release of ledger out ASAP - this month.

**Review by jwiegley — APPROVED** [review]

**Comment by tbm** [comment]
I tried to merge this before but I don't know how: "This branch cannot be rebased due to conflicts"

Maybe someone who is better with Git can do it.

**Comment by tbm** [comment]
@afh any chance you can merge this or update the PR so I can merge it?

If you can do this in the next few days, I'd merge and make a new release.

**Comment by afh** [comment]
Yes, I'm working on an update to this PR to use [utfcpp 3.2.3](https://github.com/nemtrif/utfcpp/releases/tag/v3.2.3) (released Dec 2022) and resolving the conflicts.

**Comment by tbm** [comment]
replaced by #2180

**Comment by afh** [comment]
Closing in favor of #2180

**Pull request closed without merging**
