### PR TITLE
Avoid string in amount_t::in_place_truncate

### PR DESCRIPTION
**Pull request by maxnikulin**
Do not serialize to string just to get rounded value. `in_place_roundto` should be reliable enough now.

### CODE REVIEW

**Comment by maxnikulin** [comment]
Feel free to reject this optimization attempt if you prefer to not change code that is not broken

**Comment by jwiegley** [comment]
What does `#if 2` mean? Isn't that the same as having no `if` at all?

**Comment by maxnikulin** [comment]
I do not mind to just drop current variant of code completely, anyway it can be easily found in git history. However I noticed that simple and inefficient code is preserved for some reason. That is why I decided to use the same approach and to hide current code from compiler by `#if` and `#else`.

**Comment by jwiegley** [comment]
Sure, in this case I'd just drop the version that will no longer be used. Leaving it there does not seem to be very educational, since I have a hard time convincing myself that it represents the "simpler" version of the code in the other branch...

**Comment by jwiegley** [comment]
And if you mean that the simpler version is the final one, then even more so we should delete the older, complex code.

**Comment by maxnikulin** [comment]
I have dropped older variants of `in_place_truncate`

**Review by jwiegley — APPROVED** [review]

**Pull request merged**
