### PR TITLE
Handle boost::optional<T> properly in Python types

### PR DESCRIPTION
**Pull request by davidsklar**
Setters for types wrapped in `boost::optional`, such as `item_t::note`, were broken, e.g. setting a note on a transaction resulted in garbled data that would cause Python to throw utf-8 errors when retrieving the note.

Setters that accessed strings directly, e.g. "payee" on a transaction worked fine.

The change in this PR alters the from-python conversion for optional-wrapped types based on the example at

    https://stackoverflow.com/questions/36485840/wrap-boostoptional-using-boostpython

and adds a test case to verify the behavior.

### CODE REVIEW

**Comment by tbm** [comment]
Thanks!  This needs review from @afh 

btw, why do your PRs always have a lot of merge commits.

**Comment by tbm** [comment]
Hmm, this PR contains changes we've merged already. Only commit 0edcc440332724f7c6 seems relevant but even that has changes from the change we commited already

**Comment by tbm** [comment]
@davidsklar can you clean up the commit (or open a new PR with the single change if that's easier).

I'd like to make a new release of ledger soon.

**Comment by davidsklar** [comment]
Ugh, sorry, I must have polluted my downstream master branch. I'm going to close this PR, a clean replacement is available at https://github.com/ledger/ledger/pull/2167

**Pull request closed without merging**
