### PR TITLE
Provide Docker information in README

### PR DESCRIPTION
**Pull request by alberto56**

### CODE REVIEW

**Comment by crazyh** [comment]
Not sure that this image is usable for all: it contains hard coded timezone.

**Comment by alberto56** [comment]
Hi @crazyh -- I'd be interested in obtaining more information about how ledger uses timezone information; I have also opened https://github.com/dcycle/docker-ledger/issues/2 to track this within the Docker project itself.

**Comment by crazyh** [comment]
I do not know how ledger uses timezone for calculations but it uses `strftime` so it is  probably that some operations like pricedb-related should be affected by TZ.

**Comment by alberto56** [comment]
Have just merged in a pull request which no longer uses a hard-coded timezone, see https://github.com/dcycle/docker-ledger/issues/2

**Pull request merged**
