### PR TITLE
--depth for register

### PR DESCRIPTION
**Pull request by johannesgerer**
As discussed on IRC. 

Right now the depth is hard-coded in line 475. This needs to be taken from the command-line argument "--depth" (or 0, if "--collapse" is used).

### CODE REVIEW

**Comment by jwiegley** [comment]
@johannesgerer Merged as is, thanks for your patience!

**Comment by jwiegley** [comment]
@johannesgerer What does the "3" here mean:

``` c++
value_t& collapse_posts::find_totals(account_t* account)
{
  unsigned short depth=3;

	if(depth==0)
		return totals[_("<Total>")];

  if(account->depth==depth)
    return totals[account->fullname()];
```

**Comment by jwiegley** [comment]
I'm reverting this for now, as it also has odd behavior: `--depth=1` only show postings where the account has amount in it *at depth 1*.  I.e., a posting into `Expenses:Food` doesn't show up at `depth=1`.

**Comment by johannesgerer** [comment]
I am sorry for the confusion. I think my two previous posts in this thread should answer your questions.

**Comment by jwiegley** [comment]
Ok, I think I'm just going to reject then, as I'm not sure it provides an intuitive enough experience to be worth the change to the code.

**Comment by jwiegley** [comment]
For example, I would want to see unit tests demonstrating the capabilities, and an addition to the manual explaining what this feature does for the user.  My expectation was that `--depth=2` would aggregate subtotals in the level 2 accounts.  But maybe you're saying the implementation was just incomplete?  If so, then we can revisit.

**Comment by johannesgerer** [comment]
Yes, "Right now the depth is hard-coded" and "I was just sharing my progress". The code only sets the stage for the actual functionality which is still missing.

**Comment by jwiegley** [comment]
@johannesgerer My mistake.

**Pull request merged**
