### PR TITLE
Support Approximate Balance Assertions

### PR DESCRIPTION
**Pull request by eliptus**
```
commodity STK
    format 1,000.000 STK

2014/01/01 * Statement Balance
    Brokerage                       123.456789 STK @@ 100.00 USD
    Checking                        -100.00 USD

2014/01/01 * Statement Balance
    Brokerage                       0 =~ 123.457 STK
```

### CODE REVIEW

**Comment by afh** [comment]
@eliptus Still interested in getting this merged?

**Comment by eliptus** [comment]
Oh, wow. It's been a while hasn't it...  Sorry, but as excited as I was to
start using and contributing to Ledger at the time, I quickly got
distracted.  I am not currently an active user and no longer in a position
to pursue this.

- Harpreet "Eli" Sangha

**Comment by pvinis** [comment]
@eliptus may i ask what are you using now?

**Comment by eliptus** [comment]
I started using YNAB.  I found it helped me focus more on budgeting for the
future, and worry less about accounting for the past.

On Thu, Feb 25, 2016 at 11:40 PM Pavlos Vinieratos <notifications@github.com>
wrote:

> @eliptus <https://github.com/eliptus> may i ask what are you using now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ledger/ledger/pull/329#issuecomment-189149611>.
>
-- 
- Harpreet "Eli" Sangha

**Comment by davelab6** [comment]
I guess this should be closed

**Pull request closed without merging**
