### PR TITLE
Fix build under Cygwin

### PR DESCRIPTION
**Pull request by Vanav**
Cygwin doesn't define _WIN32, and if you define it, build will fail.

### CODE REVIEW

**Comment by thdox** [comment]
There is a regression with this Pull Request. The build does not pass on osx/clang. I believe this is related to changes in src/strptime.cc

**Comment by jwiegley** [comment]
@Vanav Can you please provide a fix for this?

**Comment by Vanav** [comment]
I expected my changes are safe. Can you show error from log?

**Comment by jwiegley** [comment]
@thdox Do you have a log?  It actually built for me with 10.11/clang.

**Pull request merged**
