### PR TITLE
Manual install instruction

### PR DESCRIPTION
**Pull request by kain88-de**
The install instruction in the manual still used an old `configure` setup. I copied and adjusted the instructions from `README.md`. It would be nice if a native speaker could look over it. Thanks

### CODE REVIEW

**Comment by kain88-de** [comment]
I fixed the broken test.

**Comment by afh** [comment]
Hi @kain88-de,
I'd prefer if you could get rid of the following two commits by using `git rebase -i`:
* f42134d787fcda084aaeaa4c1f9df96ef415aa10
* 9afe61174d289df2ff8cd0804e42849f90c2d6fc

**Comment by purcell** [comment]
> I'd prefer if you could get rid of the following two commits by using git rebase -i:

ie. squash them into the other commits, not remove them completely. :-)

**Comment by afh** [comment]
@purcell As fas as I can see commit f42134d removes whitespace which is added again in 9afe611, so I'd prefer both commits to be removed form this pull request, since there is no value in them, or am I missing something?

**Comment by purcell** [comment]
Oh, I see. If that's the case, then I completely agree.

**Comment by kain88-de** [comment]
@afh done

**Comment by afh** [comment]
@kain88-de Thanks :+1:  I have two more little things I'd like before I approve this pull-request:

1. Please change this pull-request so that it is against the `next` branch.
2. and add `[ci skip]` to each commit message, since the tests are irrelevant for the continuous integration.

**Comment by kain88-de** [comment]
Done see #378

**Pull request closed without merging**
