### PR TITLE
Add flake

### PR DESCRIPTION
**Pull request by matthewbauer**
This might be useful to anyone using Nix. This allows you to use the new Nix flakes feature. If not, you can still use shell.nix or default.nix

### CODE REVIEW

**Comment by tbm** [comment]
I don't know anything about Nix.  Do all of these files have to be in the main directory or could they be moved to a sub-dir?

**Comment by purcell** [comment]
@matthewbauer heads-up that we use `default.nix` to build a ledger dev snapshot for use in the `ledger-mode` CI. The existing default.nix is broken, but it would be good to line things up so that everything works again (ideally without requiring the adoption of flakes in that other repo, personally speaking).

**Comment by akirak** [comment]
I created #2082 which would hopefully fix the CI failure in ledger-mode.

FYI: If you had flake.nix in `ledger-mode`, you could test ledger-mode against this PR without #2082 being merged into master, e.g.:

```sh
nix build --override-input ledger github:matthewbauer/ledger/add-flake
```

**Review by jwiegley — APPROVED** [review]

**Comment by jwiegley** [comment]
Pushed!

**Pull request merged**
