### PR TITLE
Fix balance assertions on accounts with virtual posts

### PR DESCRIPTION
**Pull request by daraul**
Disclaimer: I'm *completely* new to C++ projects, and I only sort of figured out how to write this test tonight by looking at existing merge requests, so if the test is bad please forgive me.

Here I attempt to reproduce error #543 with the hope being that I, or somebody else, can figure out how to fix it.

I don't know how to run the tests on my system, so I don't know where to begin debugging/fixing it, but any help will be appreciated.

### CODE REVIEW

**Comment by tbm** [comment]
@daraul thanks, but we add testcases when we commit a fix, not before. The idea is that the CI system should pass all the time. (It currently doesn't, which is a problem but that's another issue.)

**Comment by daraul** [comment]
@tbm my intention was never to leave the pipelines in a failing state, so I am working on fixing the test, and therefore the issue, but like I mentioned this is my first c++ rodeo, so progress is slow at best. A point in the right direction would be much appreciated.

**Comment by daraul** [comment]
I've hit a brick wall where I don't know what to do, so I thought I'd ask for some guidance.
Please consider case 543_a.test:

```
2018/01/01 * Opening Balance
    Assets:Checking                             $100.00
    Equity:Opening Balances

2018/01/01 * Budget
    [Assets:Checking]                           -$100.00
    [Assets:Budget:Food:Groceries]              $20.00
    [Assets:Budget:Food:Restaurants]            $80.00

2018/01/02 * Assertion
    [Assets:Checking]                           = $0.00

2018/01/02 * Assertion
    Assets:Checking                             = $100.00
```

This gives me this, as reported in #543: 

```
While parsing file "/home/daraul/Development/ledger/test/regress/543_a.test", line 14:
While balancing transaction from "/home/daraul/Development/ledger/test/regress/543_a.test", lines 13-14:
> 2018/01/02 * Assertion
>     Assets:Checking                             = $100.00
Unbalanced remainder is:
             $100.00
Amount to balance against:
             $100.00
Error: Transaction does not balance
```

However, if I swap those two assertions, it works fine: 

```
2018/01/01 * Opening Balance
    Assets:Checking                             $100.00
    Equity:Opening Balances

2018/01/01 * Budget
    [Assets:Checking]                           -$100.00
    [Assets:Budget:Food:Groceries]              $20.00
    [Assets:Budget:Food:Restaurants]            $80.00

2018/01/02 * Assertion
    Assets:Checking                             = $100.00
    
2018/01/02 * Assertion
    [Assets:Checking]                           = $0.00
```

That gives me the expected output:
```
	      $100.00  Assets:Budget:Food
              $20.00    Groceries
              $80.00    Restaurants
--------------------
             $100.00
```

I can only guess that the reason for this is that the previous virtual assertion is somehow preventing the latter real assertion from considering all the posts that it should, resulting in ledger thinking the assertion is actually an assignment, then generating a posting for that, and finding nothing to balance against, throwing this error. 

I'm still looking, but I don't know where to go about correcting this.

**Comment by daraul** [comment]
@tbm @jwiegley that should do it. I'm not sure why the pipeline failed, but all tests pass on my machine. Apologies for the initial fuss I caused.

**Comment by daraul** [comment]
I noticed `next` was updated, so I rebased this branch.

**Comment by jwiegley** [comment]
Thank you!

**Comment by tbm** [comment]
was this really ready to be merged?  And even if, the commit history should be cleaned up.

Anyway, it was commited to the next branch whereas we work on master now, so there's still time to fix this properly. ;)

**Comment by daraul** [comment]
Oh, when I opened this I believe `next` was the main branch, @tbm. Should I make another MR to clean up? What exactly needs to be cleaned up?

**Comment by jwiegley** [comment]
@tbm What remains to be done? I may have misevaluated.

**Comment by tbm** [comment]
1) I don't use balance assertions so I can't comment on this specific issue, but there are a number of open bug reports and some people who contributed in this area, so a review/ack from those would be great.

2) The commit history is a mess.  I think all of the commits should be one single commit.

But anyway, that's just me.  These are not strong objections and you can ignore me. But it was applied to next and has to be on master eventually.

(I wonder if this is a GitHub config issue or documentation issue since a lot of PRs are against next.)

**Comment by daraul** [comment]
> (I wonder if this is a GitHub config issue or documentation issue since a lot of PRs are against next.)

I think it's a documentation issue, @tbm. See the contribution guide here: https://github.com/ledger/ledger/blob/master/CONTRIBUTING.md#tips-for-contributors

**Comment by tbm** [comment]
> I think it's a documentation issue, @tbm.

Fixed, thank you @daraul

**Comment by daraul** [comment]
As for this PR, what should I do, @tbm? I don't mind creating another PR to master, and squashing the commits.

**Comment by tbm** [comment]
@daraul I hope my comments didn't come across as too negative. I'm happy you looked into this issue. I'm just overly critical and pedantic. ;)

Since @jwiegley is happy with the change, I think squashing the commits and applying to master sounds like the way to go.

**Comment by jwiegley** [comment]
@tbm Your opinion matters a great deal to me, so if @daraul is willing, let's ask for a followup PR to clean, and ping some of the other contributors in this area for review.

**Comment by tbm** [comment]
Just to explain my thinking (and again, I don't use this feature and don't know much about it): there were some fixes in that area at some point and I think some people claimed that broke something. And I know there are a number of open tickets in this area. So that's why I suggested asking those guys to review.

Maybe this fix is obvious (I honestly haven't even read the description properly). But since this feature has received some fixes and issues, I thought it would be best to get more input. I hope that explains my thinking.

Having said that, I'm happy @daraul took the initiative to look into this and to propose a fix! Thank you for that.

**Comment by daraul** [comment]
@jwiegley @tbm please see https://github.com/ledger/ledger/pull/1866

I do notice that [this test](https://github.com/ledger/ledger/blob/139beba6e99729f1c10a9e95221478f932331a02/test/regress/1057.test) fails on `master` and therefore on this new PR. I'm not sure why it fails.

**Pull request merged**
