### PR TITLE
Add conda installation instructions to README

### PR DESCRIPTION
**Pull request by twrightsman**
This will add the instructions to install the latest full release (including the build fix patches for Boost 1.70) with conda to the README.

### CODE REVIEW

**Comment by jwiegley** [comment]
Why would I include instructions for `conda`? I haven't even heard of it yet.

**Comment by twrightsman** [comment]
Conda is a package manager that is typically used to install packages into a user's home directory, so that root access is unneeded and the system environment doesn't need to be modified or filled with development libraries.
It's quite similar to homebrew, but for Linux, so I figured instructions for it would be useful to more casual Linux users, like how the homebrew instructions are in the README. Would you prefer the instructions further down near homebrew? Or would you rather not include this?

**Comment by jwiegley** [comment]
I'm happy to include it, based on your description; can you move it down near homebrew? That way we have the Mac and Linux "quick start" options near each other. Thanks!

**Comment by twrightsman** [comment]
That's great, I hope it will help adoption by more casual Linux users!
How does the current positioning look?

**Comment by jwiegley** [comment]
Great, thanks!

**Pull request merged**
