### PR TITLE
Typo in the manual: "legder"

### PR DESCRIPTION
**Pull request by aleksejrs**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.

**Comment by afh** [comment]
Hi @aleksejrs,
thanks for your contribution!
Please issue future pull request onto the `next` branch as stated in the [contributor guidelines](https://github.com/ledger/ledger/blob/master/CONTRIBUTING.md) since we're following a [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) based development model.

@purcell could you merge this into `next` as well please, otherwise `master` and `next` will diverge too much.

**Comment by purcell** [comment]
Oh crap, sorry. Didn't even check that. Will merge.

**Comment by aleksejrs** [comment]
You are welcome.

> Please issue future pull request onto the next branch as stated in the contributor guidelines 

OK, I'll try to remember to check for that next time.

**Comment by purcell** [comment]
Done.

**Pull request merged**
