### PR TITLE
Small doc typo fixes

### PR DESCRIPTION
**Pull request by jostber**

### CODE REVIEW

**Comment by jostber** [comment]
On 09.01.15,01:45, Alexis Hildebrandt wrote:
> Hi @jostber thanks for your fixes your help is much appreciated.
> What's the purpose of the empty `doc/DEVELOP.md.new` file?
> 
> Since we are moving to a [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) development as [announced on the list](https://groups.google.com/forum/#!topic/ledger-cli/s7cUVPobynI) please be so kind and issue pull request to the `next` branch in the future, thanks :relaxed: 
> 

Thanks. :) I will push to the next branch from now on. THe
doc/DEVELOP.md.new file was added by a mistake, so that can be removed. 

Regards,

Jostein

**Comment by afh** [comment]
I removed the the file added by a mistake and merged these changes into the `next branch.

**Comment by jostber** [comment]
On 09.01.15,01:45, Alexis Hildebrandt wrote:
> Hi @jostber thanks for your fixes your help is much appreciated.
> What's the purpose of the empty `doc/DEVELOP.md.new` file?
> 
> Since we are moving to a [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) development as [announced on the list](https://groups.google.com/forum/#!topic/ledger-cli/s7cUVPobynI) please be so kind and issue pull request to the `next` branch in the future, thanks :relaxed: 
> 

When I try to push to the next branch, I get this error:

remote: Permission to ledger/ledger.git denied to jostber.
fatal: unable to access 'https://github.com/ledger/ledger.git/': The
requested URL returned error: 403
Error creating pull request: Unprocessable Entity (HTTP 422)
No commits between ledger:next and jostber:jb-docfix

Can you check this? 

Jostein

**Comment by afh** [comment]
Hi @jostber,
only [members](https://github.com/orgs/ledger/people) of certain teams in [ledger github organization](https://github.com/ledger) have write access to the ledger repositories; the workflow for contributors involves issuing pull-requests, just like this one, only that from now on they should be made towards the [`next`](https://github.com/ledger/ledger/tree/next) branch.

Should you be uncertain on how to issue a pull request to other branches than the default branch have a look at the github documentation on ["Changing the branch range and destination repository"](https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository).

**Comment by jostber** [comment]
On 12.01.15,01:30, Alexis Hildebrandt wrote:
> Hi @jostber,
> only [members](https://github.com/orgs/ledger/people) of certain teams in [ledger github organization](https://github.com/ledger) have write access to the ledger repositories; the workflow for contributors involves issuing pull-requests, just like this one, only that from now on they should be made towards the [`next`](https://github.com/ledger/ledger/tree/next) branch.
> 
> Should you be uncertain on how to issue a pull request to other branches than the default branch have a look at the github documentation on ["Changing the branch range and destination repository"](https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository).
> 

Seems like I fixed it now and the pull-requests are pushed correctly.
Thanks.

Jostein

**Pull request merged**
