### PR TITLE
Convert boost::optional objects to bool explicitly.

### PR DESCRIPTION
**Pull request by jwakely**
Fixes #417.

### CODE REVIEW

**Comment by afh** [comment]
This looks quite promising. Thanks!

**Comment by thdox** [comment]
On Debian 8, with gcc 4.9 and boost 1.55, compiling is correct and test are passing (when #422 applied on next). This fixes #417. Thanks @jwakely :+1:

**Comment by thdox** [comment]
Also, from #ledger, build is passing for @Ikke, on archlinux boost 1.58 gcc 5.1.0

**Comment by afh** [comment]
Kudos @jwakely :clap: :smile:

**Comment by jwakely** [comment]
Thanks for all the testing and quick feedback! :)

**Comment by Ikke** [comment]
The build succeeded when we applied #417, which currently has been reverted. So next currently does not build without that PR.

**Comment by jwakely** [comment]
N.B. _part_ of #417 was reverted (the 48aec0f commit) but the 68c9d64 commit was not reverted and is still needed to build with Boost 1.58.0

**Comment by jwakely** [comment]
N.B. _part_ of #417 was reverted (the 48aec0f commit, which this PR replaces) but the 68c9d64 commit was not reverted and is still needed to build with Boost 1.58.0

**Comment by afh** [comment]
Exactly.

I'm doing another test on Debian 8 with 68c9d64 applied and would merge the commit if it compiles well.

**Comment by Ikke** [comment]
Sorry, I linked to the commits, instead of the reverts: 7df6a515 is the commit that reverts 68c9d64 (git blame -L710,710 src/filters.cc returns that commit that last touched that line)

**Comment by jwakely** [comment]
Oops, sorry, you're right it was reverted ... I should have just said it's still needed for Boost 1.58.0

**Comment by afh** [comment]
I just pushed  68c9d64 onto next.

**Comment by Ikke** [comment]
Build succeeded. (

**Pull request merged**
