### PR TITLE
format_t::truncate support wide characters

### PR DESCRIPTION
**Pull request by kcwu**
also add unit tests

### CODE REVIEW

**Comment by kcwu** [comment]
Hi, any chance this got review and merged?

**Comment by tbm** [comment]
@jwiegley can you review this?

**Comment by tbm** [comment]
I think this change is good but I'd prefer a review from @jwiegley

**Review by tbm — APPROVED** [review]
I was hoping for @jwiegly to review but he's quite busy.

This looks good to me, so I'll merge.  Thank you!

**Pull request merged**
