### PR TITLE
Support for `NO_COLOR` environment variable

### PR DESCRIPTION
**Pull request by nagy**
See https://no-color.org/ for more information about the variable.

### CODE REVIEW

**Review by Rahix — APPROVED** [review]
Because the great thing about standards is that there are so many, there is also the [`CLICOLOR` standard](https://bixense.com/clicolors/) with a similar goal.  But it looks like `NO_COLOR` is more widely adopted so I think this change is a good idea.

**Comment by tbm** [comment]
`report.h` has:

```
    OPTION_(report_t, no_color, DO() {
        OTHER(color).off();
      });
```

Is there a reason we can't do a similar call (not sure where though) if the environment variable is set?

**Comment by nagy** [comment]
> Is there a reason we can't do a similar call (not sure where though) if the environment variable is set?

That seems like a better way. I will see if I can make it that way.

**Comment by nagy** [comment]
I will undraft this PR once I think it is ready.

**Comment by nagy** [comment]
I have given this a try and I cannot find a suitable place to place the logic for this.

I have also found that I can get the effect that I wanted by doing:

```
export LEDGER_NO_COLOR=1
```

That is enough for my needs, so feel free to close this PR if nobody wants to take it on.

**Pull request closed without merging**
