### PR TITLE
Improve support for libedit and readline

### PR DESCRIPTION
**Pull request by afh**
This PR is an alternative approach to remedy the compilation errors mentioned in #2258 more broadly.

### CODE REVIEW

**Comment by madroach** [comment]
Hi, thanks for this proper feature test. I just now notice that OpenBSD also has libreadline in the base system, although I have no idea whether it has any relation to OpenBSD's libedit. The header file for libedit is `histedit.h`, which is not sufficient for building ledger.
Anyway, it might be enough to test just for libreadline and drop the OpenBSD specific tests altogether ?

**Comment by madroach** [comment]
I just tested this PR. It works fine on my OpenBSD.
Then I removed the 4 OpenBSD specific lines in CMakeList.txt:
``` diff
@@ -252,11 +252,6 @@ endif()

 check_library_exists(edit add_history "" HAVE_EDIT)
 find_opt_library_and_header(EDIT_PATH editline/readline.h EDIT_LIB edit HAVE_EDIT)
-# OpenBSD libedit
-if (OPENBSD AND NOT HAVE_EDIT)
-check_library_exists(edit add_history "" HAVE_READLINE)
-find_opt_library_and_header(READLINE_PATH readline/history.h READLINE_LIB edit HAVE_READLINE)
-endif (OPENBSD AND NOT HAVE_EDIT)
 if (NOT HAVE_EDIT OR HAVE_READLINE)
 check_library_exists(readline add_history "" HAVE_READLINE)
 find_opt_library_and_header(READLINE_PATH readline/history.h READLINE_LIB readline HAVE_READLINE)
```
It still builds fine and links against libreadline.

**Comment by madroach** [comment]
I am an OpenBSD developer and can prepare a patch. Given an ok by the maintainer I can (and will) see for a speedy commit. Just ping me when the release is out.

**Comment by afh** [comment]
That good to know, thanks @madroach. ℹ️ Currently there is not specific release plan or date set…

**Review by jwiegley — APPROVED** [review]

**Pull request merged**
