### PR TITLE
Let dependabot help us keep Actions config up to date

### PR DESCRIPTION
**Pull request by purcell**

### CODE REVIEW

**Comment by afh** [comment]
Thanks for the suggestion @purcell. Not being familiar with Dependabot for GitHub Actions, can you please share links to related documentation and use-cases that you think ledger will benefit from?
This would help me understand better how this can be used. 🙏

**Comment by purcell** [comment]
Essentially, with this config Dependabot will automatically open PRs in the repo to bump the versions of GitHub Actions we use here, e.g. `install-nix-action`. I've been doing this across my repos today exactly because v20 of that action is currently broken on MacOS, and v22 is fixed — Dependabot just makes such updates easy to apply.

https://docs.github.com/en/code-security/dependabot/working-with-dependabot

**Review by afh — APPROVED** [review]
Automatically created PR to update GitHub Actions you say? I'm all for it!! 🥳

**Comment by afh** [comment]
Thanks for making this change, @purcell. I took the liberty to apply the same changes to [ledger/ledger.github.io](https://github.com/ledger/ledger.github.io), so that things are up-to-date there as well.

**Comment by purcell** [comment]
Oh, good thinking. I'd already done it for `ledger-mode` too. 😄

**Comment by afh** [comment]
Excellent, @purcell! :tada:

@alerque is this something that [`ledger/vim-ledger`](https://github.com/ledger/vim-ledger) could possibly benefit from too?

**Pull request merged**
