### PR TITLE
Update to C++17

### LINKED ISSUE #2375: Failing to build with ICU 75
When doing a fresh clone and `./acprep update`, I get these errors:

```
In file included from /usr/include/unicode/uset.h:36,
                 from /usr/include/unicode/unorm2.h:35,
                 from /usr/include/unicode/unorm.h:25,
                 from /usr/include/unicode/ucol.h:17,
                 from /usr/include/unicode/coll.h:62,
                 from /usr/include/boost/regex/v5/icu.hpp:24,
                 from /usr/include/boost/regex/icu.hpp:27,
                 from /home/phil/local/src/ledger/system.hh:180,
                 from /home/phil/local/src/ledger/src/CMakeFiles/libledger.dir/cmake_pch.hxx:5,
                 from <command-line>:
/usr/include/unicode/localpointer.h:561:26: error: parameter declared ‘auto’
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
/usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
  573 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
      |                                                                            ^
/usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid
  583 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
      |                                                                              ^
/usr/include/unicode/localpointer.h:599:59: error: template argument 2 is invalid
  599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
```

```
In file included from /usr/include/unicode/unistr.h:39,
                 from /usr/include/unicode/strenum.h:20,
                 from /usr/include/unicode/locid.h:40,
                 from /usr/include/unicode/coll.h:64:
/usr/include/unicode/stringpiece.h:133:29: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
  133 |             typename = std::enable_if_t<
      |                             ^~~~~~~~~~~
/usr/include/unicode/stringpiece.h:133:24: note: ‘std::enable_if_t’ is only available from C++14 onwards
  133 |             typename = std::enable_if_t<
      |                        ^~~
/usr/include/unicode/stringpiece.h:133:40: error: expected ‘>’ before ‘<’ token
  133 |             typename = std::enable_if_t<
      |                                        ^
```

I'm not sure how to debug this. I don't have `CMakeFiles/CMakeOutput.log` or `CMakeFiles/CMakeError.log`, and searching the folder for either `enable_if_t` or `g++` doesn't find me anything else that looks like a log file. I assume I'm compiling with `g++`, that's version 14.2.1.

Tho files with the errors are both owned by icu, and I have v75.1 of that.

<details><summary>Details of ICU</summary>

```
$ pacman -Qi icu
Name            : icu
Version         : 75.1-1
Description     : International Components for Unicode library
Architecture    : x86_64
URL             : https://icu.unicode.org
Licenses        : LicenseRef-Unicode-3.0  BSD-2-Clause  BSD-3-Clause
Groups          : None
Provides        : libicudata.so=75-64  libicui18n.so=75-64  libicuio.so=75-64  libicutest.so=75-64
                  libicutu.so=75-64  libicuuc.so=75-64
Depends On      : gcc-libs  glibc  sh
Optional Deps   : None
Required By     : boost-libs  calibre  chromium  gspell  harfbuzz-icu  libxml2  nodejs  qt6-base  qt6-webengine
                  smbclient  texlive-bin  tracker3  vte3
Optional For    : xfsprogs
Conflicts With  : None
Replaces        : None
Installed Size  : 40.62 MiB
Packager        : Andreas Radke <andyrtr@archlinux.org>
Build Date      : Thu May 9 10:25:15 2024
Install Date    : Mon Jun 17 21:43:25 2024
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

(This is arch linux.)
</details>

The README says ICU is optional and (at least for now) I wouldn't mind compiling without it, but I'm not sure how to disable it.

Posting the full output below. These two lines look relevant:

```
-- Failed to find all ICU components (missing: ICU_LIBRARY) (found version "75.1")
-- Found ICU: /usr/include (found suitable version "75.1", minimum required is "63") found components: uc i18n
```

<details><summary>Full output</summary>

```
$ ./acprep update
acprep: INFO: Invoking primary phase: update
acprep: INFO: Executing phase: update
acprep: INFO: Executing phase: pull
Already up to date.
acprep: INFO: Executing phase: make
acprep: INFO: Executing phase: config
acprep: INFO: Executing phase: configure
acprep: INFO: System type is => Linux
acprep: INFO: Setting up build flavor => debug
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:84 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /usr/lib/cmake/Boost-1.83.0/BoostConfig.cmake (found suitable version "1.83.0", minimum required is "1.72") found components: date_time filesystem system iostreams regex unit_test_framework nowide
-- Failed to find all ICU components (missing: ICU_LIBRARY) (found version "75.1")
-- Found ICU: /usr/include (found suitable version "75.1", minimum required is "63") found components: uc i18n
-- Looking for getpwuid
-- Looking for getpwuid - found
-- Looking for getpwnam
-- Looking for getpwnam - found
-- Looking for ioctl
-- Looking for ioctl - found
-- Looking for isatty
-- Looking for isatty - found
-- Performing Test UNIX_PIPES_COMPILES
-- Performing Test UNIX_PIPES_COMPILES - Success
-- Performing Test BOOST_REGEX_UNICODE_RUNS
-- Performing Test BOOST_REGEX_UNICODE_RUNS - Success
-- Looking for add_history in edit
-- Looking for add_history in edit - found
-- Looking for editline/readline.h in edit
-- Looking for editline/readline.h in edit - found
-- Performing Test HAVE_WORKING_UTFCPP
-- Performing Test HAVE_WORKING_UTFCPP - Success
-- Found Python: /usr/bin/python3.12 (found version "3.12.4") found components: Interpreter
-- Configuring done (3.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/phil/local/src/ledger
[  1%] Building CXX object src/CMakeFiles/libledger.dir/cmake_pch.hxx.gch
In file included from /usr/include/unicode/uset.h:36,
                 from /usr/include/unicode/unorm2.h:35,
                 from /usr/include/unicode/unorm.h:25,
                 from /usr/include/unicode/ucol.h:17,
                 from /usr/include/unicode/coll.h:62,
                 from /usr/include/boost/regex/v5/icu.hpp:24,
                 from /usr/include/boost/regex/icu.hpp:27,
                 from /home/phil/local/src/ledger/system.hh:180,
                 from /home/phil/local/src/ledger/src/CMakeFiles/libledger.dir/cmake_pch.hxx:5,
                 from <command-line>:
/usr/include/unicode/localpointer.h:561:26: error: parameter declared ‘auto’
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
/usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
  573 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
      |                                                                            ^
/usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid
  583 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
      |                                                                              ^
/usr/include/unicode/localpointer.h:599:59: error: template argument 2 is invalid
  599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
/usr/include/unicode/uset.h:358:1: note: invalid template non-type parameter
  358 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUSetPointer, USet, uset_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/unorm2.h:286:1: note: invalid template non-type parameter
  286 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUNormalizer2Pointer, UNormalizer2, unorm2_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/uenum.h:69:1: note: invalid template non-type parameter
   69 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration, uenum_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/ucol.h:553:1: note: invalid template non-type parameter
  553 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUCollatorPointer, UCollator, ucol_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/unicode/unistr.h:39,
                 from /usr/include/unicode/strenum.h:20,
                 from /usr/include/unicode/locid.h:40,
                 from /usr/include/unicode/coll.h:64:
/usr/include/unicode/stringpiece.h:133:29: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
  133 |             typename = std::enable_if_t<
      |                             ^~~~~~~~~~~
/usr/include/unicode/stringpiece.h:133:24: note: ‘std::enable_if_t’ is only available from C++14 onwards
  133 |             typename = std::enable_if_t<
      |                        ^~~
/usr/include/unicode/stringpiece.h:133:40: error: expected ‘>’ before ‘<’ token
  133 |             typename = std::enable_if_t<
      |                                        ^
make[2]: *** [src/CMakeFiles/libledger.dir/build.make:77: src/CMakeFiles/libledger.dir/cmake_pch.hxx.gch] Error 1
make[1]: *** [CMakeFiles/Makefile2:227: src/CMakeFiles/libledger.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
acprep: ERROR: Execution failed: make
```
</details>

### PR DESCRIPTION
**Pull request by dbear496**
Updates the build to use C++17, and uses [CMAKE_CXX_STANDARD](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html) instead of setting the `-std` flag manually. Using CMAKE_CXX_STANDARD allows the C++ version to decay if/when the compiler doesn't support the requested version, so the version increase shouldn't break builds on older systems.

Fixes #2375

### CODE REVIEW

**Review by jwiegley — APPROVED** [review]
This PR seems to contain a few other changes than those related to C++17, but it all looks good to me.

**Comment by dbear496** [comment]
> This PR seems to contain a few other changes than those related to C++17, but it all looks good to me.

The reason this PR included changes from #2381 is because without them, CI checks would fail due to issues with Boost. If you merged #2381 before this PR, then it would be fine. But it looks to me like you rebased this PR onto master, which implicitly rebased #2381. And then you merged #2381 into master, so commits from #2381 are duplicated.

**Comment by dbear496** [comment]
Fixing the damage from the rebase requires rewriting history, but it you want to, you can by running 
```
git checkout master
git reset --hard d51cf4a5
git push
```

**Comment by dbear496** [comment]
Or if you prefer a linear history, you can run
```
git checkout master
git reset --hard abd4ecb5
git push 
```

**Pull request merged**
