### PR TITLE
Make Python xact.remove_post remove a post rather than add it

### PR DESCRIPTION
**Pull request by davidsklar**
The python binding was mistakenly referencing add_post rather than remove_post.

### CODE REVIEW

**Review by tbm — DISMISSED** [review]
I don't know anything about Python support but this seems kind of obvious. @afh?

**Comment by davidsklar** [comment]
Sorry, I meant to put those changes w/r/t converting boost::optional in a separate PR but seem to have committed them here LMK if you'd like those to go in a separate pull request.

**Comment by tbm** [comment]
yes, please split them

**Comment by afh** [comment]
Thanks for contributing to ledger, @davidsklar. Yes, splitting those PRs would be helpful as well as providing more context on the changes, e.g. which issues do they fix, what do they optimise, or how does ledger and its users benefit from these.

Looking forward to you PRs :)

**Comment by davidsklar** [comment]
OK -- will do. I'll close this PR and open up separate ones with the individual changes.

**Comment by tbm** [comment]
@davidsklar can you please submit these two changes as separate PRs.  I'm hoping to make a new ledger release soon.

**Pull request closed without merging**
